### PR TITLE
Refactor web frontend and remove unnecessary dependencies.

### PR DESCRIPTION
**Pull request by knadh**
- Eliminate frontend JS build step completely:
  (remove dep: NodeJS, npx, tailwind, postcss, autoprefixer)

- Declutter and cleanup index.html (8.49 KB to 3.4 KB) = ~60% savings.

- Replace tailwind with custom CSS (10.64 KB to 1.96 KB) = ~81% savings.

- Remove Google font (~100 KB) as there is very little text on the page.

- Refactor and cleanup main.js and remove tailwind styling logic.
  (2.82 KB to 1.12 KB) = ~60% savings.

- Net static asset reduction = 21.95 KB to 6.48 KB = ~70% savings
  apart from the 100+ KB elimination of Google fonts.

The update looks like this:

image

image

### CODE REVIEW

**Comment by mr-karan** [comment]
This looks great! Going through the changes.

**Comment by mr-karan** [comment]
This looks great. Only minor thing, I guess we can add a bit of spacing to label and form fields, so it doesn't look cluttered. I'll merge your PR and add this short snippet myself:

```
label {
	padding-bottom: 0.5rem;
}
```

Thanks a tonne!

**Comment by mr-karan** [comment]
Fixed line-height issue with https://github.com/mr-karan/doggo/commit/d09eb901ec403ccf07cb9da8dd77d5def79fb28d

image

**Comment by knadh** [comment]
Good spots. Forgot to add `min-width: 320px` to `.main` so that it doesn't squish beyond a certain point on unrealistically small screen sizes.

**Pull request merged**
